/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import clases.Cliente;
import clases.ClienteData;
import clases.ConexionBD;
import clases.Consulta;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class ActualizarCliente extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarCliente
     */
    int xMouse, yMouse;

    public ActualizarCliente() {
        initComponents();
        Checkestado.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtrut.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtnombre.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtapellido.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtcorreo.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtdireccion.setBackground(new java.awt.Color(0, 0, 0, 0));
        txttelefono.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtid.setBackground(new java.awt.Color(0, 0, 0, 0));

        txtdireccion.setVisible(false);
        txtid.setVisible(false);
        txtnombre.setVisible(false);
        txtapellido.setVisible(false);
        txtdireccion.setVisible(false);
        txtcorreo.setVisible(false);
        txttelefono.setVisible(false);

        lbnombre.setVisible(false);
        lbapellido.setVisible(false);
        lbdireccion.setVisible(false);
        lbcorreo.setVisible(false);
        lbtelefono.setVisible(false);
        Lbusuario6.setVisible(false);
        jsusuario5.setVisible(false);
        jsusuario3.setVisible(false);
        jsusuario1.setVisible(false);
        jsusuario2.setVisible(false);
        jsusuario4.setVisible(false);
        jsusuario6.setVisible(false);

    }
    private Cliente cliente;

    public void setCliente(Cliente entrada) {
        cliente = entrada;
        this.txtrut.setText(cliente.getRut());
        this.txtnombre.setText(cliente.getNombre());

        this.txtapellido.setText(cliente.getApellido());

        this.txtcorreo.setText(cliente.getCorreo());
        this.txtdireccion.setText(cliente.getDireccion());
        this.txttelefono.setText(cliente.getTelefono());
        int idCliente = cliente.getIdCliente();

// Convertir el ID del cliente a String (si el ID es un número)
        String idClienteString = String.valueOf(idCliente);

// Establecer el valor del campo de texto
        this.txtid.setText(idClienteString);
        this.Checkestado.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnactualizarcli = new javax.swing.JButton();
        header1 = new javax.swing.JPanel();
        exitbtn2 = new javax.swing.JPanel();
        exitTxt2 = new javax.swing.JLabel();
        exitbtn3 = new javax.swing.JPanel();
        exitTxt3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lbusuario = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        jsusuario = new javax.swing.JSeparator();
        lbnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jsusuario1 = new javax.swing.JSeparator();
        lbapellido = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jsusuario2 = new javax.swing.JSeparator();
        lbcorreo = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        lbdireccion = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jsusuario4 = new javax.swing.JSeparator();
        lbtelefono = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jsusuario5 = new javax.swing.JSeparator();
        jsusuario6 = new javax.swing.JSeparator();
        Checkestado = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        Lbusuario6 = new javax.swing.JLabel();
        jsusuario3 = new javax.swing.JSeparator();
        btnbuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(226, 173, 97));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 40));

        btnactualizarcli.setBackground(new java.awt.Color(226, 173, 97));
        btnactualizarcli.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnactualizarcli.setForeground(new java.awt.Color(0, 0, 0));
        btnactualizarcli.setText("Actualizar Datos ");
        btnactualizarcli.setBorder(null);
        btnactualizarcli.setContentAreaFilled(false);
        btnactualizarcli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnactualizarcli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnactualizarcliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnactualizarcliMouseExited(evt);
            }
        });
        btnactualizarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarcliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnactualizarcli, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnactualizarcli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, -1));

        header1.setBackground(new java.awt.Color(0, 0, 0));
        header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header1MouseDragged(evt);
            }
        });
        header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                header1MouseReleased(evt);
            }
        });

        exitbtn2.setBackground(new java.awt.Color(0, 0, 0));
        exitbtn2.setForeground(new java.awt.Color(0, 0, 0));

        exitTxt2.setBackground(new java.awt.Color(255, 255, 255));
        exitTxt2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt2.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt2.setText("X");
        exitTxt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt2.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtn2Layout = new javax.swing.GroupLayout(exitbtn2);
        exitbtn2.setLayout(exitbtn2Layout);
        exitbtn2Layout.setHorizontalGroup(
            exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitbtn2Layout.createSequentialGroup()
                    .addComponent(exitTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        exitbtn2Layout.setVerticalGroup(
            exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitbtn2Layout.createSequentialGroup()
                    .addComponent(exitTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        exitbtn3.setBackground(new java.awt.Color(0, 0, 0));

        exitTxt3.setBackground(new java.awt.Color(255, 255, 255));
        exitTxt3.setFont(new java.awt.Font("Roboto Light", 0, 48)); // NOI18N
        exitTxt3.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt3.setText("-");
        exitTxt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt3.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtn3Layout = new javax.swing.GroupLayout(exitbtn3);
        exitbtn3.setLayout(exitbtn3Layout);
        exitbtn3Layout.setHorizontalGroup(
            exitbtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
        exitbtn3Layout.setVerticalGroup(
            exitbtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap(586, Short.MAX_VALUE)
                .addComponent(exitbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGroup(header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Actualizar Datos del Cliente ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 350, 50));

        Lbusuario.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Lbusuario.setForeground(new java.awt.Color(0, 0, 0));
        Lbusuario.setText("Rut");
        jPanel1.add(Lbusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 60, 20));

        txtrut.setBackground(new java.awt.Color(255, 255, 255));
        txtrut.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtrut.setForeground(new java.awt.Color(0, 0, 0));
        txtrut.setBorder(null);
        txtrut.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtrut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtrutMousePressed(evt);
            }
        });
        txtrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutActionPerformed(evt);
            }
        });
        txtrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrutKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutKeyTyped(evt);
            }
        });
        jPanel1.add(txtrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 40));
        jPanel1.add(jsusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 140, 10));

        lbnombre.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbnombre.setForeground(new java.awt.Color(0, 0, 0));
        lbnombre.setText("Nombre");
        jPanel1.add(lbnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 60, 20));

        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombre.setBorder(null);
        txtnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnombreMousePressed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 280, 40));
        jPanel1.add(jsusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 280, 10));

        lbapellido.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbapellido.setForeground(new java.awt.Color(0, 0, 0));
        lbapellido.setText("Apellidos");
        jPanel1.add(lbapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 70, 20));

        txtapellido.setBackground(new java.awt.Color(255, 255, 255));
        txtapellido.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(0, 0, 0));
        txtapellido.setBorder(null);
        txtapellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtapellidoMousePressed(evt);
            }
        });
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellidoKeyPressed(evt);
            }
        });
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 280, 40));
        jPanel1.add(jsusuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, 10));

        lbcorreo.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbcorreo.setForeground(new java.awt.Color(0, 0, 0));
        lbcorreo.setText("Correo Electrónico");
        jPanel1.add(lbcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 130, 20));

        txtcorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreo.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtcorreo.setBorder(null);
        txtcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcorreoMousePressed(evt);
            }
        });
        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcorreoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcorreoKeyReleased(evt);
            }
        });
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 280, 40));

        lbdireccion.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbdireccion.setForeground(new java.awt.Color(0, 0, 0));
        lbdireccion.setText("Dirección");
        jPanel1.add(lbdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 70, 20));

        txtdireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtdireccion.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtdireccion.setBorder(null);
        txtdireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtdireccionMousePressed(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
        });
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 280, 40));
        jPanel1.add(jsusuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 280, 10));

        lbtelefono.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbtelefono.setForeground(new java.awt.Color(0, 0, 0));
        lbtelefono.setText("Teléfono");
        jPanel1.add(lbtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 60, 20));

        txttelefono.setBackground(new java.awt.Color(255, 255, 255));
        txttelefono.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txttelefono.setForeground(new java.awt.Color(0, 0, 0));
        txttelefono.setBorder(null);
        txttelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txttelefonoMousePressed(evt);
            }
        });
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 280, 40));
        jPanel1.add(jsusuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 280, 10));
        jPanel1.add(jsusuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 280, 10));

        Checkestado.setBackground(new java.awt.Color(255, 255, 255));
        Checkestado.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Checkestado.setForeground(new java.awt.Color(0, 0, 0));
        Checkestado.setText("Activar Cliente");
        Checkestado.setToolTipText("");
        Checkestado.setBorder(null);
        Checkestado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Checkestado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckestadoStateChanged(evt);
            }
        });
        Checkestado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckestadoMouseClicked(evt);
            }
        });
        Checkestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckestadoActionPerformed(evt);
            }
        });
        Checkestado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CheckestadoPropertyChange(evt);
            }
        });
        jPanel1.add(Checkestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facil.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 110));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(255, 255, 255));
        txtid.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 0, 0));
        txtid.setBorder(null);
        txtid.setEnabled(false);
        txtid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtidMousePressed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 60, 30));

        Lbusuario6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Lbusuario6.setForeground(new java.awt.Color(0, 0, 0));
        Lbusuario6.setText("Id");
        jPanel1.add(Lbusuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 20, 20));
        jPanel1.add(jsusuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 60, 10));

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busq.png"))); // NOI18N
        btnbuscar.setBorder(null);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fotos123.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 26, 680, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarcliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnactualizarcliMouseEntered
        // TODO add your handling code here:

        btnactualizarcli.setBackground(new Color(243, 197, 140));
    }//GEN-LAST:event_btnactualizarcliMouseEntered

    private void btnactualizarcliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnactualizarcliMouseExited
        // TODO add your handling code here:
        btnactualizarcli.setBackground(new Color(255, 174, 97));
    }//GEN-LAST:event_btnactualizarcliMouseExited

    private void btnactualizarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarcliActionPerformed
        // TODO add your handling code here:
        Cliente mod = new Cliente(); // Crear una instancia de la clase Usuarios para almacenar los datos del usuario
        if (txtrut.getText().isEmpty() || txtnombre.getText().isEmpty() || txtapellido.getText().isEmpty() || txtcorreo.getText().isEmpty() || txtdireccion.getText().isEmpty() || txttelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Rellenar Campos");
        } else {
            Consulta con = new Consulta();
            ConexionBD db = new ConexionBD();
            mod.setIdCliente(cliente.getIdCliente());

            mod.setRut(txtrut.getText());
            mod.setNombre(txtnombre.getText());
            mod.setApellido(txtapellido.getText());
            mod.setCorreo(txtcorreo.getText());
            mod.setDireccion(txtdireccion.getText());
            mod.setTelefono(txttelefono.getText());
            mod.setEstado(Checkestado.isSelected() ? "true" : "false");

            try {
                db.getConexion();

                if (con.actualizarCliente(mod)) {
                    this.cliente.getIdCliente();
                    this.Checkestado.isSelected();
                    
                    this.setVisible(false);
                    VerClientes f1 = new VerClientes();
                    f1.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "ERRor");
                }

            } catch (Exception e) {
            }

        }


    }//GEN-LAST:event_btnactualizarcliActionPerformed

    private void exitTxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA CERRAR EL PROGRAMA?", "CERRAR PROGRAMAR", a);
        if (resultado == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitTxt2MouseClicked

    private void exitTxt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseEntered
        // TODO add your handling code here:
        exitbtn2.setBackground(Color.red);
        exitTxt2.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt2MouseEntered

    private void exitTxt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseExited
        // TODO add your handling code here:
        exitbtn2.setBackground(Color.black);
        exitTxt2.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt2MouseExited

    private void exitTxt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseClicked
        // TODO add your handling code here:
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_exitTxt3MouseClicked

    private void exitTxt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseEntered
        // TODO add your handling code here:

        exitbtn3.setBackground(Color.gray);
        exitTxt3.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt3MouseEntered

    private void exitTxt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseExited
        // TODO add your handling code here:
        exitbtn3.setBackground(Color.black);
        exitTxt3.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt3MouseExited

    private void header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header1MouseDragged

    private void header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header1MousePressed

    private void header1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_header1MouseReleased

    private void txtrutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrutMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutMousePressed

    private void txtrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutActionPerformed
        // TODO add your handling code here:
        String rut = txtrut.getText();
        if (!rut.isEmpty()) {
            rut = rut.replace(".", "");
            rut = rut.replace("-", "");

        }
    }//GEN-LAST:event_txtrutActionPerformed

    private void txtrutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutKeyPressed

    private void txtrutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyReleased

    }//GEN-LAST:event_txtrutKeyReleased

    private void txtrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyTyped
        char validar = evt.getKeyChar();
        if (!Character.isDigit(validar) && Character.compare(validar, 'k') != 0) {

            evt.consume();
            return;

        }
        if (txtrut.getText().length() >= 12) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se debe ingresar como máximo 12 caracteres");
            return;
        }

        if (txtrut.getText().length() == 2 || txtrut.getText().length() == 6) {
            txtrut.setText(txtrut.getText() + '.');
        } else if (txtrut.getText().length() == 10) {
            txtrut.setText(txtrut.getText() + '-');
        }
    }//GEN-LAST:event_txtrutKeyTyped

    private void txtnombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreMousePressed

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyPressed

    private void txtapellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoMousePressed

    private void txtapellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoKeyPressed

    private void txtcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoMousePressed

    private void txtcorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoKeyPressed

    private void txtcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoKeyReleased

    private void txtdireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdireccionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionMousePressed

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyPressed

    private void txttelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttelefonoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoMousePressed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void txttelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoKeyPressed

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        // TODO add your handling code here:

        char tecla;
        tecla = evt.getKeyChar();

        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
        if (txttelefono.getText().length() >= 9) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se debe ingresar como máximo 9 caracteres");
            return;
        }
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void CheckestadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckestadoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckestadoStateChanged

    private void CheckestadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckestadoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_CheckestadoMouseClicked

    private void CheckestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckestadoActionPerformed
        // TODO add your handling code here:
        Checkestado.setEnabled(!Checkestado.isEnabled());
    }//GEN-LAST:event_CheckestadoActionPerformed

    private void CheckestadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CheckestadoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckestadoPropertyChange

    private void txtidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidMousePressed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyPressed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        if (txtrut.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No se ha podido realizar la busqueda, rellenar campo rut.");

        } else {
            Consulta objetocliente = new Consulta();
            int idCliente = objetocliente.buscarut1(txtid, txtrut, txtnombre, txtapellido, txtcorreo, txtdireccion, txttelefono);
            ClienteData.getInstance().setIdCliente(idCliente);
            lbnombre.setVisible(true);
            jsusuario1.setVisible(true);
            lbapellido.setVisible(true);
            jsusuario2.setVisible(true);
            lbdireccion.setVisible(true);
            jsusuario4.setVisible(true);
            lbcorreo.setVisible(true);
            jsusuario6.setVisible(true);
            lbtelefono.setVisible(true);
            jsusuario5.setVisible(true);
            jsusuario3.setVisible(true);
            txtnombre.setVisible(true);
            txtapellido.setVisible(true);
            txtdireccion.setVisible(true);
            txtcorreo.setVisible(true);
            txttelefono.setVisible(true);
            jsusuario1.setVisible(true);
            txtid.setVisible(true);
            Lbusuario6.setVisible(true);

        }

    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Checkestado;
    private javax.swing.JLabel Lbusuario;
    private javax.swing.JLabel Lbusuario6;
    private javax.swing.JButton btnactualizarcli;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel exitTxt2;
    private javax.swing.JLabel exitTxt3;
    private javax.swing.JPanel exitbtn2;
    private javax.swing.JPanel exitbtn3;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jsusuario;
    private javax.swing.JSeparator jsusuario1;
    private javax.swing.JSeparator jsusuario2;
    private javax.swing.JSeparator jsusuario3;
    private javax.swing.JSeparator jsusuario4;
    private javax.swing.JSeparator jsusuario5;
    private javax.swing.JSeparator jsusuario6;
    private javax.swing.JLabel lbapellido;
    private javax.swing.JLabel lbcorreo;
    private javax.swing.JLabel lbdireccion;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbtelefono;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtrut;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
