/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import clases.ClienteData;
import clases.Consulta;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class DatosCliente extends javax.swing.JFrame {

    /**
     * Creates new form DatosCliente
     */
    int xMouse, yMouse;
    public static String dato;

    public DatosCliente() {
        initComponents();
        txtrut.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtnombres.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtapellidos.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtcorreo.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtdireccion.setBackground(new java.awt.Color(0, 0, 0, 0));
        txttelefono.setBackground(new java.awt.Color(0, 0, 0, 0));

        txtdireccion.setVisible(false);

        txtnombres.setVisible(false);
        txtapellidos.setVisible(false);
        txtdireccion.setVisible(false);
        txtcorreo.setVisible(false);
        txttelefono.setVisible(false);

        lbnombres.setVisible(false);
        lbapellidos.setVisible(false);
        lbdireccion.setVisible(false);
        lbcorreo.setVisible(false);
        lbtelefono.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        exitbtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        exitbtn1 = new javax.swing.JPanel();
        exitTxt1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        lbtelefono = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        lbcorreo = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        lbdireccion = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        lbapellidos = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        lbnombres = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtrut = new javax.swing.JTextField();
        lbrut = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        loginBtn3 = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jsusuario = new javax.swing.JSeparator();
        header1 = new javax.swing.JPanel();
        exitbtn2 = new javax.swing.JPanel();
        exitTxt2 = new javax.swing.JLabel();
        exitbtn3 = new javax.swing.JPanel();
        exitTxt3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                headerMouseReleased(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setBackground(new java.awt.Color(0, 0, 0));
        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(0, 0, 0));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtnLayout = new javax.swing.GroupLayout(exitbtn);
        exitbtn.setLayout(exitbtnLayout);
        exitbtnLayout.setHorizontalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitbtnLayout.createSequentialGroup()
                    .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        exitbtnLayout.setVerticalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitbtnLayout.createSequentialGroup()
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        exitbtn1.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt1.setBackground(new java.awt.Color(0, 0, 0));
        exitTxt1.setFont(new java.awt.Font("Roboto Light", 0, 48)); // NOI18N
        exitTxt1.setForeground(new java.awt.Color(0, 0, 0));
        exitTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt1.setText("-");
        exitTxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt1.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtn1Layout = new javax.swing.GroupLayout(exitbtn1);
        exitbtn1.setLayout(exitbtn1Layout);
        exitbtn1Layout.setHorizontalGroup(
            exitbtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
        exitbtn1Layout.setVerticalGroup(
            exitbtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(711, 711, 711)
                .addComponent(exitbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(226, 173, 97));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn.setText("Continuar");
        loginBtn.setToolTipText("");
        loginBtn.setBorder(null);
        loginBtn.setContentAreaFilled(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 110, -1));

        lbtelefono.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbtelefono.setForeground(new java.awt.Color(0, 0, 0));
        lbtelefono.setText("Teléfono");
        jPanel2.add(lbtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 70, 40));

        txttelefono.setBackground(new java.awt.Color(255, 255, 255));
        txttelefono.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txttelefono.setForeground(new java.awt.Color(0, 0, 0));
        txttelefono.setActionCommand("<Not Set>");
        txttelefono.setBorder(null);
        txttelefono.setCaretColor(new java.awt.Color(0, 0, 0));
        txttelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txttelefono.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txttelefono.setEnabled(false);
        txttelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txttelefonoMousePressed(evt);
            }
        });
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelefonoKeyReleased(evt);
            }
        });
        jPanel2.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, 30));

        lbcorreo.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbcorreo.setForeground(new java.awt.Color(0, 0, 0));
        lbcorreo.setText("Correo Electronico");
        jPanel2.add(lbcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 130, 40));

        txtcorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreo.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtcorreo.setActionCommand("<Not Set>");
        txtcorreo.setBorder(null);
        txtcorreo.setCaretColor(new java.awt.Color(0, 0, 0));
        txtcorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtcorreo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtcorreo.setEnabled(false);
        txtcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcorreoMousePressed(evt);
            }
        });
        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcorreoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcorreoKeyReleased(evt);
            }
        });
        jPanel2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 250, 30));

        lbdireccion.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbdireccion.setForeground(new java.awt.Color(0, 0, 0));
        lbdireccion.setText("Dirección");
        jPanel2.add(lbdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, 30));

        txtdireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtdireccion.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtdireccion.setActionCommand("<Not Set>");
        txtdireccion.setBorder(null);
        txtdireccion.setCaretColor(new java.awt.Color(0, 0, 0));
        txtdireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtdireccion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtdireccion.setEnabled(false);
        txtdireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtdireccionMousePressed(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccionKeyReleased(evt);
            }
        });
        jPanel2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 330, 30));

        lbapellidos.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbapellidos.setForeground(new java.awt.Color(0, 0, 0));
        lbapellidos.setText("Apellidos");
        jPanel2.add(lbapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 70, 40));

        txtapellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidos.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtapellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtapellidos.setActionCommand("<Not Set>");
        txtapellidos.setBorder(null);
        txtapellidos.setCaretColor(new java.awt.Color(0, 0, 0));
        txtapellidos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtapellidos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtapellidos.setEnabled(false);
        txtapellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtapellidosMousePressed(evt);
            }
        });
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellidosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidosKeyReleased(evt);
            }
        });
        jPanel2.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 190, 30));

        lbnombres.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbnombres.setForeground(new java.awt.Color(0, 0, 0));
        lbnombres.setText("Nombres");
        jPanel2.add(lbnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 70, 40));

        txtnombres.setBackground(new java.awt.Color(255, 255, 255));
        txtnombres.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtnombres.setForeground(new java.awt.Color(0, 0, 0));
        txtnombres.setActionCommand("<Not Set>");
        txtnombres.setBorder(null);
        txtnombres.setCaretColor(new java.awt.Color(0, 0, 0));
        txtnombres.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtnombres.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtnombres.setEnabled(false);
        txtnombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnombresMousePressed(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombresKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombresKeyReleased(evt);
            }
        });
        jPanel2.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 190, 30));

        txtrut.setBackground(new java.awt.Color(255, 255, 255));
        txtrut.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        txtrut.setForeground(new java.awt.Color(0, 0, 0));
        txtrut.setActionCommand("<Not Set>");
        txtrut.setBorder(null);
        txtrut.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtrut.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtrut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtrutMousePressed(evt);
            }
        });
        txtrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutActionPerformed(evt);
            }
        });
        txtrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrutKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutKeyTyped(evt);
            }
        });
        jPanel2.add(txtrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 30));

        lbrut.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbrut.setForeground(new java.awt.Color(0, 0, 0));
        lbrut.setText("Rut");
        jPanel2.add(lbrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 30, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logotransparente.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 190, 130));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Datos del Cliente");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 210, 50));

        jPanel5.setBackground(new java.awt.Color(226, 173, 97));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn3.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn3.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn3.setText("Cerrar Sesión");
        loginBtn3.setToolTipText("");
        loginBtn3.setBorder(null);
        loginBtn3.setContentAreaFilled(false);
        loginBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn3MouseExited(evt);
            }
        });
        loginBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, -1));

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busq.png"))); // NOI18N
        btnbuscar.setBorder(null);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));
        jPanel2.add(jsusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 160, 10));

        header1.setBackground(new java.awt.Color(0, 0, 0));
        header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header1MouseDragged(evt);
            }
        });
        header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                header1MouseReleased(evt);
            }
        });

        exitbtn2.setBackground(new java.awt.Color(0, 0, 0));
        exitbtn2.setForeground(new java.awt.Color(0, 0, 0));

        exitTxt2.setBackground(new java.awt.Color(255, 255, 255));
        exitTxt2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt2.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt2.setText("X");
        exitTxt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt2.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtn2Layout = new javax.swing.GroupLayout(exitbtn2);
        exitbtn2.setLayout(exitbtn2Layout);
        exitbtn2Layout.setHorizontalGroup(
            exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitbtn2Layout.createSequentialGroup()
                    .addComponent(exitTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        exitbtn2Layout.setVerticalGroup(
            exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitbtn2Layout.createSequentialGroup()
                    .addComponent(exitTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        exitbtn3.setBackground(new java.awt.Color(0, 0, 0));

        exitTxt3.setBackground(new java.awt.Color(255, 255, 255));
        exitTxt3.setFont(new java.awt.Font("Roboto Light", 0, 48)); // NOI18N
        exitTxt3.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt3.setText("-");
        exitTxt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt3.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtn3Layout = new javax.swing.GroupLayout(exitbtn3);
        exitbtn3.setLayout(exitbtn3Layout);
        exitbtn3Layout.setHorizontalGroup(
            exitbtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
        exitbtn3Layout.setVerticalGroup(
            exitbtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap(636, Short.MAX_VALUE)
                .addComponent(exitbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGroup(header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondopan.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA CERRAR EL PROGRAMA?", "CERRAR PROGRAMAR", a);
        if (resultado == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        // TODO add your handling code here:
        exitbtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        // TODO add your handling code here:
        exitbtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt1MouseClicked
        // TODO add your handling code here:
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_exitTxt1MouseClicked

    private void exitTxt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt1MouseEntered
        // TODO add your handling code here:

        exitbtn1.setBackground(Color.gray);
        exitTxt1.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt1MouseEntered

    private void exitTxt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt1MouseExited
        // TODO add your handling code here:
        exitbtn1.setBackground(Color.white);
        exitTxt1.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt1MouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_headerMouseReleased

    private void txtnombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombresMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombresMousePressed

    private void txtnombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombresKeyPressed

    private void txtnombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombresKeyReleased

    private void txtapellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidosMousePressed

    private void txtapellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidosKeyPressed

    private void txtapellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidosKeyReleased

    private void txtdireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdireccionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionMousePressed

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyPressed

    private void txtdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyReleased

    private void txtcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoMousePressed

    private void txtcorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoKeyPressed

    private void txtcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoKeyReleased

    private void txttelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttelefonoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoMousePressed

    private void txttelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoKeyPressed

    private void txttelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoKeyReleased

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        // TODO add your handling code here:

        loginBtn.setBackground(new Color(243, 197, 140));
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        // TODO add your handling code here:
        loginBtn.setBackground(new Color(255, 174, 97));
    }//GEN-LAST:event_loginBtnMouseExited

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:

        if (txtnombres.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Realice la busqueda");
        } else {
            dato = txtrut.getText();
            this.setVisible(false);
            Selección f1 = new Selección();

            // f1.setDato(txtrut.getText());
            f1.setVisible(true);

        }


    }//GEN-LAST:event_loginBtnActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        if (txtrut.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No se ha podido realizar la busqueda, rellenar campo rut.");

        } else {
            Consulta objetocliente = new Consulta();
            int idCliente = objetocliente.buscarut(txtrut, txtnombres, txtapellidos, txtcorreo, txtdireccion, txttelefono);
            ClienteData.getInstance().setIdCliente(idCliente);
            lbnombres.setVisible(true);
            lbapellidos.setVisible(true);
            lbdireccion.setVisible(true);
            lbcorreo.setVisible(true);
            lbtelefono.setVisible(true);
            txtnombres.setVisible(true);
            txtapellidos.setVisible(true);
            txtdireccion.setVisible(true);
            txtcorreo.setVisible(true);
            txttelefono.setVisible(true);


        }
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (!Character.isDigit(validar) && Character.compare(validar, 'k') != 0) {

            evt.consume();
            return;

        }
        if (txtrut.getText().length() >= 12) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se debe ingresar como máximo 12 caracteres");
            return;
        }

        if (txtrut.getText().length() == 2 || txtrut.getText().length() == 6) {
            txtrut.setText(txtrut.getText() + '.');
        } else if (txtrut.getText().length() == 10) {
            txtrut.setText(txtrut.getText() + '-');
        }

    }//GEN-LAST:event_txtrutKeyTyped

    private void txtrutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutKeyReleased

    private void txtrutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutKeyPressed

    private void txtrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtrutActionPerformed

    private void txtrutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrutMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutMousePressed

    private void exitTxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA CERRAR EL PROGRAMA?", "CERRAR PROGRAMAR", a);
        if (resultado == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitTxt2MouseClicked

    private void exitTxt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseEntered
        // TODO add your handling code here:
        exitbtn2.setBackground(Color.red);
        exitTxt2.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt2MouseEntered

    private void exitTxt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseExited
        // TODO add your handling code here:
        exitbtn2.setBackground(Color.black);
        exitTxt2.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt2MouseExited

    private void exitTxt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseClicked
        // TODO add your handling code here:
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_exitTxt3MouseClicked

    private void exitTxt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseEntered
        // TODO add your handling code here:

        exitbtn3.setBackground(Color.gray);
        exitTxt3.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt3MouseEntered

    private void exitTxt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseExited
        // TODO add your handling code here:
        exitbtn3.setBackground(Color.black);
        exitTxt3.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt3MouseExited

    private void header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header1MouseDragged

    private void header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header1MousePressed

    private void header1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_header1MouseReleased

    private void loginBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn3MouseEntered
        // TODO add your handling code here:

        loginBtn.setBackground(new Color(243, 197, 140));
    }//GEN-LAST:event_loginBtn3MouseEntered

    private void loginBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn3MouseExited
        // TODO add your handling code here:
        loginBtn.setBackground(new Color(255, 174, 97));
    }//GEN-LAST:event_loginBtn3MouseExited

    private void loginBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn3ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        Login f1 = new Login();
        f1.setVisible(true);

    }//GEN-LAST:event_loginBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel exitTxt1;
    private javax.swing.JLabel exitTxt2;
    private javax.swing.JLabel exitTxt3;
    private javax.swing.JPanel exitbtn;
    private javax.swing.JPanel exitbtn1;
    private javax.swing.JPanel exitbtn2;
    private javax.swing.JPanel exitbtn3;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jsusuario;
    private javax.swing.JLabel lbapellidos;
    private javax.swing.JLabel lbcorreo;
    private javax.swing.JLabel lbdireccion;
    private javax.swing.JLabel lbnombres;
    private javax.swing.JLabel lbrut;
    private javax.swing.JLabel lbtelefono;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton loginBtn3;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtrut;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

}
