/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import clases.ClienteData;
import clases.Consulta;
import clases.PanesData;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;

import javax.swing.JOptionPane;
import static vistas.DatosCliente.dato;

/**
 *
 * @author carlo
 */
public class Selección extends javax.swing.JFrame {

    int xMouse, yMouse;
    Consulta consultas = new Consulta();
    public static String dato;

    /**
     * Creates new form Selección
     */
    public Selección() {
        initComponents();
        System.out.println(DatosCliente.dato);
        txtpan1.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtpan2.setBackground(new java.awt.Color(0, 0, 0, 1));

        txtpan3.setBackground(new java.awt.Color(0, 0, 0, 1));

        txtpan4.setBackground(new java.awt.Color(0, 0, 0, 1));

        txtpan5.setBackground(new java.awt.Color(0, 0, 0, 1));
        t1.setBackground(new java.awt.Color(0, 0, 0, 1));
        tprecio.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtruts.setText(DatosCliente.dato);

        Limpiar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        header1 = new javax.swing.JPanel();
        exitbtn2 = new javax.swing.JPanel();
        exitTxt2 = new javax.swing.JLabel();
        exitbtn3 = new javax.swing.JPanel();
        exitTxt3 = new javax.swing.JLabel();
        jsusuario4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpan1 = new javax.swing.JTextField();
        jsusuario = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        loginBtn4 = new javax.swing.JButton();
        Lbusuario = new javax.swing.JLabel();
        Lbusuario1 = new javax.swing.JLabel();
        txtpan2 = new javax.swing.JTextField();
        jsusuario1 = new javax.swing.JSeparator();
        txtpan3 = new javax.swing.JTextField();
        jsusuario2 = new javax.swing.JSeparator();
        txtpan4 = new javax.swing.JTextField();
        jsusuario3 = new javax.swing.JSeparator();
        Lbusuario2 = new javax.swing.JLabel();
        Lbusuario3 = new javax.swing.JLabel();
        Lbusuario4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        loginBtn2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        loginBtn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        txtpan5 = new javax.swing.JTextField();
        tprecio = new javax.swing.JTextField();
        Lbusuario5 = new javax.swing.JLabel();
        Lbusuario6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        loginBtn3 = new javax.swing.JButton();
        txtruts = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setEditable(false);
        t1.setBackground(new java.awt.Color(255, 255, 255));
        t1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setActionCommand("<Not Set>");
        t1.setBorder(null);
        t1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t1MousePressed(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 120, 40));

        header1.setBackground(new java.awt.Color(0, 0, 0));
        header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header1MouseDragged(evt);
            }
        });
        header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                header1MouseReleased(evt);
            }
        });

        exitbtn2.setBackground(new java.awt.Color(0, 0, 0));
        exitbtn2.setForeground(new java.awt.Color(0, 0, 0));

        exitTxt2.setBackground(new java.awt.Color(255, 255, 255));
        exitTxt2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt2.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt2.setText("X");
        exitTxt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt2.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtn2Layout = new javax.swing.GroupLayout(exitbtn2);
        exitbtn2.setLayout(exitbtn2Layout);
        exitbtn2Layout.setHorizontalGroup(
            exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitbtn2Layout.createSequentialGroup()
                    .addComponent(exitTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        exitbtn2Layout.setVerticalGroup(
            exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitbtn2Layout.createSequentialGroup()
                    .addComponent(exitTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        exitbtn3.setBackground(new java.awt.Color(0, 0, 0));

        exitTxt3.setBackground(new java.awt.Color(255, 255, 255));
        exitTxt3.setFont(new java.awt.Font("Roboto Light", 0, 48)); // NOI18N
        exitTxt3.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt3.setText("-");
        exitTxt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt3.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtn3Layout = new javax.swing.GroupLayout(exitbtn3);
        exitbtn3.setLayout(exitbtn3Layout);
        exitbtn3Layout.setHorizontalGroup(
            exitbtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
        exitbtn3Layout.setVerticalGroup(
            exitbtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap(706, Short.MAX_VALUE)
                .addComponent(exitbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGroup(header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jsusuario4.setBackground(new java.awt.Color(0, 0, 0));
        jsusuario4.setForeground(new java.awt.Color(0, 0, 0));
        jsusuario4.setRequestFocusEnabled(false);
        jPanel1.add(jsusuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 120, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logofondo_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 190, 120));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("RUT CLIENTE :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 40));

        txtpan1.setBackground(new java.awt.Color(255, 255, 255));
        txtpan1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtpan1.setForeground(new java.awt.Color(255, 255, 255));
        txtpan1.setActionCommand("<Not Set>");
        txtpan1.setBorder(null);
        txtpan1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtpan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpan1MousePressed(evt);
            }
        });
        txtpan1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpan1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpan1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpan1KeyTyped(evt);
            }
        });
        jPanel1.add(txtpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 100, 40));

        jsusuario.setBackground(new java.awt.Color(0, 0, 0));
        jsusuario.setForeground(new java.awt.Color(0, 0, 0));
        jsusuario.setRequestFocusEnabled(false);
        jPanel1.add(jsusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 100, 10));

        jPanel6.setBackground(new java.awt.Color(226, 173, 97));
        jPanel6.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn4.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn4.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn4.setText("Cerrar Sesión");
        loginBtn4.setToolTipText("");
        loginBtn4.setBorder(null);
        loginBtn4.setContentAreaFilled(false);
        loginBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn4MouseExited(evt);
            }
        });
        loginBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(loginBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));

        Lbusuario.setBackground(new java.awt.Color(255, 255, 255));
        Lbusuario.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Lbusuario.setForeground(new java.awt.Color(255, 255, 255));
        Lbusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbusuario.setText("Precio Total");
        jPanel1.add(Lbusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 120, 20));

        Lbusuario1.setBackground(new java.awt.Color(255, 255, 255));
        Lbusuario1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Lbusuario1.setForeground(new java.awt.Color(255, 255, 255));
        Lbusuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbusuario1.setText("Pan Hallulla");
        jPanel1.add(Lbusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, -1));

        txtpan2.setBackground(new java.awt.Color(255, 255, 255));
        txtpan2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtpan2.setForeground(new java.awt.Color(255, 255, 255));
        txtpan2.setActionCommand("<Not Set>");
        txtpan2.setBorder(null);
        txtpan2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtpan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpan2MousePressed(evt);
            }
        });
        txtpan2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpan2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpan2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpan2KeyTyped(evt);
            }
        });
        jPanel1.add(txtpan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 120, 40));

        jsusuario1.setBackground(new java.awt.Color(0, 0, 0));
        jsusuario1.setForeground(new java.awt.Color(0, 0, 0));
        jsusuario1.setRequestFocusEnabled(false);
        jPanel1.add(jsusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 120, 10));

        txtpan3.setBackground(new java.awt.Color(255, 255, 255));
        txtpan3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtpan3.setForeground(new java.awt.Color(255, 255, 255));
        txtpan3.setActionCommand("<Not Set>");
        txtpan3.setBorder(null);
        txtpan3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtpan3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpan3MousePressed(evt);
            }
        });
        txtpan3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpan3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpan3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpan3KeyTyped(evt);
            }
        });
        jPanel1.add(txtpan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 100, 40));

        jsusuario2.setBackground(new java.awt.Color(0, 0, 0));
        jsusuario2.setForeground(new java.awt.Color(0, 0, 0));
        jsusuario2.setRequestFocusEnabled(false);
        jPanel1.add(jsusuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 100, 10));

        txtpan4.setBackground(new java.awt.Color(255, 255, 255));
        txtpan4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtpan4.setForeground(new java.awt.Color(255, 255, 255));
        txtpan4.setActionCommand("<Not Set>");
        txtpan4.setBorder(null);
        txtpan4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtpan4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpan4MousePressed(evt);
            }
        });
        txtpan4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpan4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpan4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpan4KeyTyped(evt);
            }
        });
        jPanel1.add(txtpan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, 40));

        jsusuario3.setBackground(new java.awt.Color(0, 0, 0));
        jsusuario3.setForeground(new java.awt.Color(0, 0, 0));
        jsusuario3.setRequestFocusEnabled(false);
        jPanel1.add(jsusuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, 10));

        Lbusuario2.setBackground(new java.awt.Color(255, 255, 255));
        Lbusuario2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Lbusuario2.setForeground(new java.awt.Color(255, 255, 255));
        Lbusuario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbusuario2.setText("Pan Marraqueta");
        jPanel1.add(Lbusuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 120, 20));

        Lbusuario3.setBackground(new java.awt.Color(255, 255, 255));
        Lbusuario3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Lbusuario3.setForeground(new java.awt.Color(255, 255, 255));
        Lbusuario3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbusuario3.setText("Pan Colisa");
        jPanel1.add(Lbusuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 100, 20));

        Lbusuario4.setBackground(new java.awt.Color(255, 255, 255));
        Lbusuario4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Lbusuario4.setForeground(new java.awt.Color(255, 255, 255));
        Lbusuario4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbusuario4.setText("Pan Molde");
        jPanel1.add(Lbusuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 80, 20));

        jPanel4.setBackground(new java.awt.Color(226, 173, 97));
        jPanel4.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn2.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn2.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn2.setText("Limpiar datos");
        loginBtn2.setBorder(null);
        loginBtn2.setContentAreaFilled(false);
        loginBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn2MouseExited(evt);
            }
        });
        loginBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jPanel3.setBackground(new java.awt.Color(226, 173, 97));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn1.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn1.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn1.setText("Regresar");
        loginBtn1.setBorder(null);
        loginBtn1.setContentAreaFilled(false);
        loginBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn1MouseExited(evt);
            }
        });
        loginBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, -1));

        jPanel2.setBackground(new java.awt.Color(226, 173, 97));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn.setText("Guardar");
        loginBtn.setBorder(null);
        loginBtn.setContentAreaFilled(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 100, -1));

        txtpan5.setBackground(new java.awt.Color(255, 255, 255));
        txtpan5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtpan5.setForeground(new java.awt.Color(255, 255, 255));
        txtpan5.setActionCommand("<Not Set>");
        txtpan5.setBorder(null);
        txtpan5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtpan5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpan5MousePressed(evt);
            }
        });
        txtpan5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpan5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpan5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpan5KeyTyped(evt);
            }
        });
        jPanel1.add(txtpan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 120, 40));

        tprecio.setEditable(false);
        tprecio.setBackground(new java.awt.Color(255, 255, 255));
        tprecio.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tprecio.setForeground(new java.awt.Color(255, 255, 255));
        tprecio.setActionCommand("<Not Set>");
        tprecio.setBorder(null);
        tprecio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tprecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tprecioMousePressed(evt);
            }
        });
        tprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tprecioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tprecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tprecioKeyTyped(evt);
            }
        });
        jPanel1.add(tprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 120, 40));

        Lbusuario5.setBackground(new java.awt.Color(255, 255, 255));
        Lbusuario5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Lbusuario5.setForeground(new java.awt.Color(255, 255, 255));
        Lbusuario5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbusuario5.setText("Pan Amasado");
        jPanel1.add(Lbusuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 120, 20));

        Lbusuario6.setBackground(new java.awt.Color(255, 255, 255));
        Lbusuario6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Lbusuario6.setForeground(new java.awt.Color(255, 255, 255));
        Lbusuario6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbusuario6.setText("Total Kilos");
        jPanel1.add(Lbusuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 120, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ingrese Cantidad Kilogramos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 350, 60));

        jPanel5.setBackground(new java.awt.Color(226, 173, 97));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn3.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn3.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn3.setText("Calcular");
        loginBtn3.setBorder(null);
        loginBtn3.setContentAreaFilled(false);
        loginBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn3MouseExited(evt);
            }
        });
        loginBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        txtruts.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        txtruts.setForeground(new java.awt.Color(255, 255, 255));
        txtruts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutsKeyTyped(evt);
            }
        });
        jPanel1.add(txtruts, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 150, 20));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagen1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtpan1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpan1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan1MousePressed

    private void txtpan1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan1KeyPressed

    private void txtpan1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtpan1KeyReleased

    private void txtpan2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpan2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan2MousePressed

    private void txtpan2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan2KeyPressed

    private void txtpan2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan2KeyReleased

    private void txtpan3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpan3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan3MousePressed

    private void txtpan3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan3KeyPressed

    private void txtpan3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan3KeyReleased

    private void txtpan4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpan4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan4MousePressed

    private void txtpan4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan4KeyPressed

    private void txtpan4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan4KeyReleased

    private void t1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1MousePressed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyPressed

    private void t1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyReleased

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_loginBtnMouseExited

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
      if (txtpan1.getText().isEmpty()||txtpan2.getText().isEmpty()||txtpan3.getText().isEmpty()||txtpan4.getText().isEmpty()||txtpan5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Si el Cliente no compro kilogramos deje el campo con el digito 0", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        }
        Date fecha = new Date();

        int Hallulla = Integer.parseInt(txtpan1.getText());
        int Marraqueta = Integer.parseInt(txtpan2.getText());
        int Colisa = Integer.parseInt(txtpan3.getText());
        int Molde = Integer.parseInt(txtpan4.getText());
        int Amasado = Integer.parseInt(txtpan5.getText());
        String kilos = t1.getText();
        String precio = tprecio.getText();
        int idCliente = ClienteData.getInstance().getIdCliente();
         int idPanes = PanesData.getInstance().getIdPanes();
         if (t1.getText().isEmpty() || tprecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Antes de Guardar la información, debe calcular los kilogramos.","AVISO", JOptionPane.INFORMATION_MESSAGE);
        }else{
              try {

            consultas.guardarPan(fecha, kilos, precio, idCliente, idPanes);
            JOptionPane.showMessageDialog(null, "Datos Guardados Correctamente", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println(e);
        }

             
         }

       

    }//GEN-LAST:event_loginBtnActionPerformed

    private void loginBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1MouseEntered

    private void loginBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1MouseExited

    private void loginBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DatosCliente f1 = new DatosCliente();
        f1.setVisible(true);


    }//GEN-LAST:event_loginBtn1ActionPerformed

    private void loginBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn2MouseEntered

    private void loginBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn2MouseExited

    private void loginBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn2ActionPerformed
        // TODO add your handling code here:
        
        if (txtpan1.getText().isEmpty()||txtpan2.getText().isEmpty()||txtpan3.getText().isEmpty()||txtpan4.getText().isEmpty()||txtpan5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encunetran datos para limpiar", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        } else {

            int a = JOptionPane.YES_NO_OPTION;
            int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA LIMPIAR LOS DATOS?", "ADVERTENCIA", a);
            Limpiar();
        }


    }//GEN-LAST:event_loginBtn2ActionPerformed

    private void txtpan1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan1KeyTyped
        // TODO add your handling code here:

        char tecla;
        tecla = evt.getKeyChar();

        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }

    }//GEN-LAST:event_txtpan1KeyTyped

    private void txtpan2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan2KeyTyped
        // TODO add your handling code here:
        char tecla;
        tecla = evt.getKeyChar();

        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtpan2KeyTyped

    private void txtpan3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan3KeyTyped
        // TODO add your handling code here:
        char tecla;
        tecla = evt.getKeyChar();

        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtpan3KeyTyped

    private void txtpan4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan4KeyTyped
        // TODO add your handling code here:
        char tecla;
        tecla = evt.getKeyChar();

        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtpan4KeyTyped

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
        char tecla;
        tecla = evt.getKeyChar();

        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_t1KeyTyped

    private void txtpan5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpan5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan5MousePressed

    private void txtpan5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan5KeyPressed

    private void txtpan5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan5KeyReleased

    private void txtpan5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpan5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpan5KeyTyped

    private void tprecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tprecioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tprecioMousePressed

    private void tprecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tprecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tprecioKeyPressed

    private void tprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tprecioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tprecioKeyReleased

    private void tprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tprecioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tprecioKeyTyped

    private void loginBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn3MouseEntered

    private void loginBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn3MouseExited

    private void loginBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn3ActionPerformed
        // TODO add your handling code here:
        final double PRECIO_POR_KG = 1;

// Obtener los valores de los campos de texto
        double n1 = Double.parseDouble(txtpan1.getText());
        double n2 = Double.parseDouble(txtpan2.getText());
        double n3 = Double.parseDouble(txtpan3.getText());
        double n4 = Double.parseDouble(txtpan4.getText());
        double n5 = Double.parseDouble(txtpan5.getText());

// Calcular el precio
        double precio = (n1 + n2 + n3 + n4 + n5) * PRECIO_POR_KG;
        int precioEntero = (int) Math.round(precio);
        tprecio.setText("$ " + String.valueOf(precioEntero));
        String resultado = String.valueOf(precio) + " KG";
        resultado = resultado.replace(".0", "");
        t1.setText(resultado);
        if (txtpan1.getText().isEmpty() || txtpan2.getText().isEmpty() || txtpan3.getText().isEmpty() || txtpan4.getText().isEmpty() || txtpan5.getText().isEmpty()) {

        }

    }//GEN-LAST:event_loginBtn3ActionPerformed

    private void exitTxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA CERRAR EL PROGRAMA?", "CERRAR PROGRAMAR", a);
        if (resultado == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitTxt2MouseClicked

    private void exitTxt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseEntered
        // TODO add your handling code here:
        exitbtn2.setBackground(Color.red);
        exitTxt2.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt2MouseEntered

    private void exitTxt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseExited
        // TODO add your handling code here:
        exitbtn2.setBackground(Color.black);
        exitTxt2.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt2MouseExited

    private void exitTxt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseClicked
        // TODO add your handling code here:
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_exitTxt3MouseClicked

    private void exitTxt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseEntered
        // TODO add your handling code here:

        exitbtn3.setBackground(Color.gray);
        exitTxt3.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt3MouseEntered

    private void exitTxt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseExited
        // TODO add your handling code here:
        exitbtn3.setBackground(Color.black);
        exitTxt3.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt3MouseExited

    private void header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header1MouseDragged

    private void header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header1MousePressed

    private void header1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_header1MouseReleased

    private void loginBtn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn4MouseEntered
        // TODO add your handling code here:

        loginBtn.setBackground(new Color(243, 197, 140));
    }//GEN-LAST:event_loginBtn4MouseEntered

    private void loginBtn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn4MouseExited
        // TODO add your handling code here:
        loginBtn.setBackground(new Color(255, 174, 97));
    }//GEN-LAST:event_loginBtn4MouseExited

    private void loginBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn4ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        Login f1 = new Login();
        f1.setVisible(true);
    }//GEN-LAST:event_loginBtn4ActionPerformed

    private void txtrutsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutsKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (!Character.isDigit(validar) && Character.compare(validar, 'k') != 0) {

            evt.consume();
            return;

        }
        if (txtruts.getText().length() >= 12) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se debe ingresar como máximo 12 caracteres");
            return;
        }

        if (txtruts.getText().length() == 2 || txtruts.getText().length() == 6) {
            txtruts.setText(txtruts.getText() + '.');
        } else if (txtruts.getText().length() == 10) {
            txtruts.setText(txtruts.getText() + '-');
        }
    }//GEN-LAST:event_txtrutsKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selección.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selección.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selección.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selección.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selección().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbusuario;
    private javax.swing.JLabel Lbusuario1;
    private javax.swing.JLabel Lbusuario2;
    private javax.swing.JLabel Lbusuario3;
    private javax.swing.JLabel Lbusuario4;
    private javax.swing.JLabel Lbusuario5;
    private javax.swing.JLabel Lbusuario6;
    private javax.swing.JLabel exitTxt2;
    private javax.swing.JLabel exitTxt3;
    private javax.swing.JPanel exitbtn2;
    private javax.swing.JPanel exitbtn3;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jsusuario;
    private javax.swing.JSeparator jsusuario1;
    private javax.swing.JSeparator jsusuario2;
    private javax.swing.JSeparator jsusuario3;
    private javax.swing.JSeparator jsusuario4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton loginBtn1;
    private javax.swing.JButton loginBtn2;
    private javax.swing.JButton loginBtn3;
    private javax.swing.JButton loginBtn4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField tprecio;
    private javax.swing.JTextField txtpan1;
    private javax.swing.JTextField txtpan2;
    private javax.swing.JTextField txtpan3;
    private javax.swing.JTextField txtpan4;
    private javax.swing.JTextField txtpan5;
    private javax.swing.JLabel txtruts;
    // End of variables declaration//GEN-END:variables
 private void Limpiar() {
        txtpan1.setText("");
        txtpan2.setText("");
        txtpan3.setText("");
        txtpan4.setText("");
        txtpan5.setText("");
        tprecio.setText("");
        t1.setText("");

    }
}
