/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import clases.Consulta;
import java.awt.Color;
import static java.awt.Color.black;
import java.awt.Font;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class VerEmpleados extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Administrador
     */
    public VerEmpleados() {
        initComponents();
        mostrarEmpleados();

        jTable1.setRowHeight(30);

        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.white);
        jTable1.setSelectionBackground(Color.gray);
        jTable1.setBackground(black);
        jTable1.getTableHeader().setForeground(new Color(0, 0, 0));
        jTable1.getTableHeader().setFont(new Font("Agency FB", Font.BOLD, 18));
        txtrut.setBackground(new java.awt.Color(0, 0, 0, 1));

        //Ajuste de columna id
        int fila = 0; // La fila que deseas ajustar (recuerda que los índices empiezan en 0)
        int columna = 0; // La columna que deseas ajustar (recuerda que los índices empiezan en 0)
        int anchoDeseado = 40; // El ancho deseado para la celda en píxeles (valor más pequeño)

        jTable1.getColumnModel().getColumn(columna).setPreferredWidth(anchoDeseado);

         int filaa = 1; // La fila que deseas ajustar (recuerda que los índices empiezan en 0)
        int columnaa = 1; // La columna que deseas ajustar (recuerda que los índices empiezan en 0)
        int anchoDeseadoo = 120; // El ancho deseado para la celda en píxeles (valor más pequeño)

        jTable1.getColumnModel().getColumn(columnaa).setPreferredWidth(anchoDeseadoo);

        int filaaa = 2; // La fila que deseas ajustar (recuerda que los índices empiezan en 0)
        int columnaaa = 2; // La columna que deseas ajustar (recuerda que los índices empiezan en 0)
        int anchoDeseadooo = 90; // El ancho deseado para la celda en píxeles (valor más pequeño)

        jTable1.getColumnModel().getColumn(columnaaa).setPreferredWidth(anchoDeseadooo);

        int filaaaa = 3; // La fila que deseas ajustar (recuerda que los índices empiezan en 0)
        int columnaaaa = 3; // La columna que deseas ajustar (recuerda que los índices empiezan en 0)
        int anchoDeseadoooo = 120; // El ancho deseado para la celda en píxeles (valor más pequeño)

        jTable1.getColumnModel().getColumn(columnaaaa).setPreferredWidth(anchoDeseadoooo);

        int filaaaaa = 4; // La fila que deseas ajustar (recuerda que los índices empiezan en 0)
        int columnaaaaa = 4; // La columna que deseas ajustar (recuerda que los índices empiezan en 0)
        int anchoDeseadooooo = 300; // El ancho deseado para la celda en píxeles (valor más pequeño)

        jTable1.getColumnModel().getColumn(columnaaaaa).setPreferredWidth(anchoDeseadooooo);

        int filaaaaaa = 5; // La fila que deseas ajustar (recuerda que los índices empiezan en 0)
        int columnaaaaaa = 5; // La columna que deseas ajustar (recuerda que los índices empiezan en 0)
        int anchoDeseadoooooo = 300; // El ancho deseado para la celda en píxeles (valor más pequeño)
        jTable1.getColumnModel().getColumn(columnaaaaaa).setPreferredWidth(anchoDeseadoooooo);

                int filaaaaaaa = 6; // La fila que deseas ajustar (recuerda que los índices empiezan en 0)
        int columnaaaaaaa = 6; // La columna que deseas ajustar (recuerda que los índices empiezan en 0)
        int anchoDeseadooooooo = 120; // El ancho deseado para la celda en píxeles (valor más pequeño)
        jTable1.getColumnModel().getColumn(columnaaaaaaa).setPreferredWidth(anchoDeseadooooooo);
        Limpiar();


    }

    public void mostrarEmpleados() {
        Consulta logica = new Consulta();

        DefaultTableModel modelo = logica.mostrarEmpleados();

        jTable1.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        loginBtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        header1 = new javax.swing.JPanel();
        exitbtn2 = new javax.swing.JPanel();
        exitTxt2 = new javax.swing.JLabel();
        exitbtn3 = new javax.swing.JPanel();
        exitTxt3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtrut = new javax.swing.JTextField();
        jsusuario = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        loginBtn2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        loginBtn4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        loginBtn3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logopequeño.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 140, 70));

        jPanel6.setBackground(new java.awt.Color(226, 173, 97));
        jPanel6.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn1.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn1.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn1.setText("Cerrar Sesión");
        loginBtn1.setToolTipText("");
        loginBtn1.setBorder(null);
        loginBtn1.setContentAreaFilled(false);
        loginBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn1MouseExited(evt);
            }
        });
        loginBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 50));

        jPanel3.setBackground(new java.awt.Color(235, 112, 19));

        jButton2.setBackground(new java.awt.Color(235, 112, 19));
        jButton2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Buscar");
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 40));

        header1.setBackground(new java.awt.Color(0, 0, 0));
        header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header1MouseDragged(evt);
            }
        });
        header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                header1MouseReleased(evt);
            }
        });

        exitbtn2.setBackground(new java.awt.Color(0, 0, 0));
        exitbtn2.setForeground(new java.awt.Color(0, 0, 0));

        exitTxt2.setBackground(new java.awt.Color(255, 255, 255));
        exitTxt2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt2.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt2.setText("X");
        exitTxt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt2.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtn2Layout = new javax.swing.GroupLayout(exitbtn2);
        exitbtn2.setLayout(exitbtn2Layout);
        exitbtn2Layout.setHorizontalGroup(
            exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitbtn2Layout.createSequentialGroup()
                    .addComponent(exitTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        exitbtn2Layout.setVerticalGroup(
            exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(exitbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitbtn2Layout.createSequentialGroup()
                    .addComponent(exitTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        exitbtn3.setBackground(new java.awt.Color(0, 0, 0));

        exitTxt3.setBackground(new java.awt.Color(255, 255, 255));
        exitTxt3.setFont(new java.awt.Font("Roboto Light", 0, 48)); // NOI18N
        exitTxt3.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt3.setText("-");
        exitTxt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt3.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtn3Layout = new javax.swing.GroupLayout(exitbtn3);
        exitbtn3.setLayout(exitbtn3Layout);
        exitbtn3Layout.setHorizontalGroup(
            exitbtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
        exitbtn3Layout.setVerticalGroup(
            exitbtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap(976, Short.MAX_VALUE)
                .addComponent(exitbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGroup(header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 30));

        jTable1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 900, 490));

        txtrut.setBackground(new java.awt.Color(255, 255, 255));
        txtrut.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtrut.setForeground(new java.awt.Color(255, 255, 255));
        txtrut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtrut.setActionCommand("<Not Set>");
        txtrut.setBorder(null);
        txtrut.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtrut.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtrut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtrutMousePressed(evt);
            }
        });
        txtrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutActionPerformed(evt);
            }
        });
        txtrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrutKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutKeyTyped(evt);
            }
        });
        jPanel1.add(txtrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 160, 30));
        jPanel1.add(jsusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 160, 10));

        jPanel9.setBackground(new java.awt.Color(255, 153, 102));

        jButton4.setBackground(new java.awt.Color(255, 153, 102));
        jButton4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("PDF");
        jButton4.setToolTipText("");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jPanel4.setBackground(new java.awt.Color(235, 112, 19));

        jButton3.setBackground(new java.awt.Color(235, 112, 19));
        jButton3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Exportar Tabla");
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jPanel5.setBackground(new java.awt.Color(226, 173, 97));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn2.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn2.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn2.setText("Limpiar datos");
        loginBtn2.setBorder(null);
        loginBtn2.setContentAreaFilled(false);
        loginBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn2MouseExited(evt);
            }
        });
        loginBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 120, 50));

        jPanel8.setBackground(new java.awt.Color(226, 173, 97));
        jPanel8.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn4.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn4.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn4.setText("Modificar Datos del Empleado");
        loginBtn4.setToolTipText("");
        loginBtn4.setBorder(null);
        loginBtn4.setContentAreaFilled(false);
        loginBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn4MouseExited(evt);
            }
        });
        loginBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 230, 50));

        jPanel7.setBackground(new java.awt.Color(226, 173, 97));
        jPanel7.setPreferredSize(new java.awt.Dimension(120, 40));

        loginBtn3.setBackground(new java.awt.Color(226, 173, 97));
        loginBtn3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        loginBtn3.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn3.setText("Volver al Menú");
        loginBtn3.setToolTipText("");
        loginBtn3.setBorder(null);
        loginBtn3.setContentAreaFilled(false);
        loginBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn3MouseExited(evt);
            }
        });
        loginBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 110, 50));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Empleados Registrados");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 390, 50));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA CERRAR EL PROGRAMA?", "CERRAR PROGRAMAR", a);
        if (resultado == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitTxt2MouseClicked

    private void exitTxt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseEntered
        // TODO add your handling code here:
        exitbtn2.setBackground(Color.red);
        exitTxt2.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt2MouseEntered

    private void exitTxt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseExited
        // TODO add your handling code here:
        exitbtn2.setBackground(Color.black);
        exitTxt2.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt2MouseExited

    private void exitTxt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseClicked
        // TODO add your handling code here:
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_exitTxt3MouseClicked

    private void exitTxt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseEntered
        // TODO add your handling code here:

        exitbtn3.setBackground(Color.gray);
        exitTxt3.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt3MouseEntered

    private void exitTxt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseExited
        // TODO add your handling code here:
        exitbtn3.setBackground(Color.black);
        exitTxt3.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt3MouseExited

    private void header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header1MouseDragged

    private void header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header1MousePressed

    private void header1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_header1MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Consulta consultas = new Consulta();

        String rut = txtrut.getText();


    

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtrutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrutMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutMousePressed

    private void txtrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutActionPerformed

    private void txtrutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutKeyPressed

    private void txtrutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutKeyReleased

    private void txtrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (!Character.isDigit(validar) && Character.compare(validar, 'k') != 0) {

            evt.consume();
            return;

        }
        if (txtrut.getText().length() >= 12) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se debe ingresar como máximo 12 caracteres");
            return;
        }

        if (txtrut.getText().length() == 2 || txtrut.getText().length() == 6) {
            txtrut.setText(txtrut.getText() + '.');
        } else if (txtrut.getText().length() == 10) {
            txtrut.setText(txtrut.getText() + '-');
        }
    }//GEN-LAST:event_txtrutKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Consulta consultas = new Consulta();

        try {
            consultas = new Consulta();
            consultas.exportarExcel(jTable1);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void loginBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn2MouseEntered

    private void loginBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn2MouseExited

    private void loginBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn2ActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_loginBtn2ActionPerformed

    private void loginBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1MouseEntered

    private void loginBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1MouseExited

    private void loginBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login f1 = new Login();
        f1.setVisible(true);


    }//GEN-LAST:event_loginBtn1ActionPerformed

    private void loginBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn3MouseEntered

    private void loginBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn3MouseExited

    private void loginBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuDueño f1 = null;
        try {
            f1 = new MenuDueño();
        } catch (SQLException ex) {
            Logger.getLogger(VerEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        f1.setVisible(true);
    }//GEN-LAST:event_loginBtn3ActionPerformed

    private void loginBtn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn4MouseEntered

    private void loginBtn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn4MouseExited

    private void loginBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn4ActionPerformed
        // TODO add your handling code here:
        Consulta consultas = new Consulta();
        String Hallulla = jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString();
        consultas.EliminarClientes(Integer.parseInt(Hallulla));
        int selectedRow = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        if (selectedRow >= 0) {
            int modelRow = jTable1.convertRowIndexToModel(selectedRow);
            model.removeRow(modelRow);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila para eliminar.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_loginBtn4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitTxt2;
    private javax.swing.JLabel exitTxt3;
    private javax.swing.JPanel exitbtn2;
    private javax.swing.JPanel exitbtn3;
    private javax.swing.JPanel header1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSeparator jsusuario;
    private javax.swing.JButton loginBtn1;
    private javax.swing.JButton loginBtn2;
    private javax.swing.JButton loginBtn3;
    private javax.swing.JButton loginBtn4;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables
private void Limpiar() {
        txtrut.setText("");
  

    }
}
